nelmio_api_doc:
    documentation:
        info:
            title: Test App Wallet!
            description: Test documentations!
            version: 1.0.0
    areas:
        path_patterns: # an array of regexps
            - ^/v1(?!/doc$)
