language: php
sudo: false
php:
  - 7.4

cache:
  directories:
    - $HOME/.composer/cache/files
    - ./bin/.phpunit

before_install:
  - composer self-update

install:
  - COMPOSER_MEMORY_LIMIT=-1 composer install
  - ./bin/console server:start
  - ./vendor/bin/codecept build

script:
  - ./vendor/bin/codecept run
