language: php
sudo: true
php:
  - 7.1
services:
  - docker
cache:
  directories:
    - $HOME/.composer/cache/files
    - ./bin/.phpunit
    - docker_images

env:
  global:
    - SYMFONY_DEPRECATIONS_HELPER=0
    - APP_ENV="dev"

before_install:
#  - echo "extension=zip.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer self-update

install:
  - COMPOSER_MEMORY_LIMIT=-1 composer install
  - docker run -u $UID -v $PWD/var:/app -w /app nouchka/sqlite3 data.db
  - ./bin/console cache:clear
  - ./bin/console doctrine:schema:create
  - ./bin/console doctrine:migrations:migrate -n
  - ./vendor/bin/codecept build
  - ./bin/console server:start 0.0.0.0:8888

script:
  - composer check-cs
  - composer phpstan
  - ./bin/console app:currency-rate-update
  - ./vendor/bin/codecept run
