language: php
sudo: true
php:
  - 7.1
services:
  - docker
cache:
  directories:
    - $HOME/.composer/cache/files
    - ./bin/.phpunit
    - docker_images

env:
  global:
    - DOCKER_COMPOSE_VERSION=1.24.1
    - SYMFONY_DEPRECATIONS_HELPER=0
    - APP_ENV="dev"

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - composer self-update
  - docker-compose build

install:
  - docker run -u $UID -v $PWD/var:/app -w /app nouchka/sqlite3 data.sqlite
  - docker ps
  - docker-compose run --rm app composer install
  - docker-compose run --rm app ./bin/console doctrine:schema:create
  - docker-compose run --rm app ./bin/console doctrine:migrations:migrate -n
  - docker-compose run --rm app ./bin/console assets:install
  - docker-compose run --rm app ./vendor/bin/codecept build


script:
  - docker-compose run --rm app composer check-cs
  - docker-compose run --rm app composer phpstan
  - docker-compose run --rm app ./bin/console app:currency-rate-update
  - ./bin/console server:start 0.0.0.0:8888
  - docker-compose run --rm app ./vendor/bin/codecept run
