language: php
sudo: false
php:
  - 7.1
services:
  - docker
cache:
  directories:
    - $HOME/.composer/cache/files
    - ./bin/.phpunit
    - docker_images

before_install:
  - echo "extension=zip.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - docker run -u $UID -v $PWD/var:/app -w /app nouchka/sqlite3 data.db
  - composer self-update

install:
  - COMPOSER_MEMORY_LIMIT=-1 composer install
  - ./bin/console doctrine:schema:create
  - ./bin/console doctrine:migrations:migrate -n
  - ./vendor/bin/codecept build
  - ./bin/console server:start

script:
  - ./vendor/bin/codecept run
