language: php
sudo: true
php:
  - 7.1
services:
  - docker
cache:
  directories:
    - $HOME/.composer/cache/files
    - ./bin/.phpunit
    - docker_images

env:
  global:
    - DOCKER_COMPOSE_VERSION=1.24.1
    - SYMFONY_DEPRECATIONS_HELPER=0
    - APP_ENV="dev"
    - DSHELL="docker-compose run -u $UID:$UID --rm app"

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - composer self-update
  - docker-compose build

install:
  - bash -c "$DSHELL ./build.sh"
  - bash -c "$DSHELL ./vendor/bin/codecept build"
  - bash -c "$DSHELL composer check-cs"
  - bash -c "$DSHELL composer phpstan"
script:
  - docker-compose up -d
  - bash -c "$DSHELL ./vendor/bin/codecept run"
