# Создание пользователя

POST http://localhost:8888/v1/user
Content-Type: application/json

{
  "name": "Vasilisa Petrova",
  "wallet_currency": "USD"
}

### получение пользователя

GET http://localhost:8888/v1/user/2

### получение кошелька

GET http://localhost:8888/v1/user/2/wallet/2

### получение баланса

GET http://localhost:8888/v1/user/2/wallet/2/balance

### Положить дениги на счёт рубли

POST http://localhost:8888/v1/user/2/wallet/2/operation
Content-Type: application/json

{
  "currency": "RUB",
  "value": 100,
  "type": "debit",
  "cause": "refund"
}

### Положить дениги на счёт доллары

POST http://localhost:8888/v1/user/2/wallet/2/operation
Content-Type: application/json

{
  "currency": "USD",
  "value": 1,
  "type": "debit",
  "cause": "refund"
}

###
